name: Actions for llm

on:
  push:
    branches:
      - main
      - dev
      - test
jobs:
    DEV:
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/dev' 
      steps:
        - uses: actions/checkout@v4

        - name: Create .env file from secret
          run: echo "${{ secrets.ENV_FILE }}" > backend/.env

        - name: Build docker compose
          run: docker compose up --build -d

        - name: Sleep 30 seconds
          uses: jakejarvis/wait-action@master
          with:
            time: '30s'

        - name: Compose stop
          run: docker compose stop
          
    TEST:
        runs-on: ubuntu-latest
        environment: TEST

        if: github.ref == 'refs/heads/test'
        steps:
            - uses: actions/checkout@v4

            - name: Get Python
              uses: actions/setup-python@v5 
              with:
                python-version: '3.12' 
            
            - name: Install requirements
              run: pip install -r backend/requirements.txt

            - name: Run Test Script
              run: pytest -v backend/test_app.py

