name: Actions for llm

on:
  push:
    branches:
      - main
      - dev
      - test
jobs:

    TEST:
        runs-on: ubuntu-latest
        environment: TEST

        if: github.ref == 'refs/heads/test'
        steps:
            - uses: actions/checkout@v4

            - name: Get Python
              uses: actions/setup-python@v5 
              with:
                python-version: '3.12' 
                
            - name: Create .env file from secret
              run: echo "${{ secrets.ENV_FILE }}" > backend/.env

            - name: Build docker compose
              run: docker compose up --build -d
                 
            - name: Run Test Script
              run: pytest -v backend/test_app.py

