name: Actions for llm

on:
  push:
    branches:
      - main
      - dev
      - test
jobs:
  
    TEST:
        runs-on: ubuntu-latest
        environment: TEST

        if: github.ref == 'refs/heads/test'
        steps:
            - uses: actions/checkout@v4

            - name: Get Python
              uses: actions/setup-python@v5 
              with:
                python-version: '3.12' 
            
            - name: Install requirements
              run: pip install -r backend/requirements.txt

            - name: Run Test Script
              run: pytest -v backend/test_app.py

